# Recibir todas las matriculas
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/all' \
  -H 'accept: */*'

# Obtener cursos disponibles
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/available/3/1' \
  -H 'accept: */*'

# Obtener matrículas por ID de usuario
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/user/3' \
  -H 'accept: */*'

# Obtener matrículas por ID de escuela
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/school/1' \
  -H 'accept: */*'

# Obtener matrículas por ID de usuario y ID de escuela
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/certificate/3/1' \
  -H 'accept: */*'

# Obtener detalles de Matricula
curl -X 'GET' \
  'http://localhost:8004/api/v1/Enrollments/1' \
  -H 'accept: */*'

# Crear Matricula
curl -X 'POST' \
  'http://localhost:8004/api/v1/Enrollments/enroll/3/1' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "courses": [
    {
      "id": "course1",
      "group": "A"
    }
  ]
}'

# Actualizar Matrícula
curl -X 'PUT' \
  'http://localhost:8004/api/v1/Enrollments/enroll/1' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "studentId": "1",
  "schoolId": "1",
  "fullName": "Shinji Ikari",
  "academicPerformance": 1,
  "credits": 28,
  "courses": [
    {"id": "1", "group": "A"},
    {"id": "3", "group": "C"}
  ],
  "schoolName": "Evangelion"
}'

# Eliminar Matrícula
curl -X 'DELETE' \
  'http://localhost:8004/api/v1/Enrollments/enroll/1' \
  -H 'accept: */*'
