### New Requests
### Login
POST http://localhost:8001/api/auth/login
{
  "email": "user1@example.com",
  "password": "User@123"
}

### Login as Admin
POST http://localhost:8001/api/auth/login
{
  "email": "admin@example.com",
  "password": "Admin@123"
}


### Register
POST http://localhost:8001/api/auth/register
{
  "id": "string",
  "name": "string",
  "email": "user3@example.com",
  "password": "string",
  "confirmPassword": "string"
}




### Create Admin
POST http://localhost:8001/api/admin/create
Content-Type: application/json

{
    "UserName": "adminuser",
    "Password": "securepassword123",
    "FullName": "John Admin",
    "Role": 1
}

### Create Student DONT WORKS
POST http://localhost:8001/api/user/create
Content-Type: application/json

{
    "UserName": "studentuser",
    "Password": "securepassword123",
    "FullName": "Jane Student",
    "Role": 0,
    "CUI": "CUI123456",
    "Email": "jane.student@example.com",
    "Courses": []
}



### Get Users Admins
GET  http://localhost:8001/api/admin/all

### Login and get Token
POST http://localhost:8001/api/authentication/login
Content-Type: application/json

{
    "userId": 1,
    "username": "adminuser"
}

# dotnet add package coverlet.msbuild

# dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
# test/test.csproj
# dotnet test test/test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura