### Register Admin First Time
POST http://localhost:8001/api/auth/register
{
    "Name": "Admin User",
    "Email": "admin@example.com",
    "Password": "Admin@123",
    "ConfirmPassword": "Admin@123",
    "Role": "Admin"
}


curl -X POST http://localhost:8001/api/auth/register/admin \
  -H "Content-Type: application/json" \
  -d '{
    "name": "string",
    "email": "admin@example.com",
    "password": "Admin123!",
    "confirmPassword": "Admin123!",
    "role": "ADMIN",
    "phoneNumber": "+1234567890"
    
    }'

### Register Student
curl -X POST http://localhost:8001/api/auth/register/student \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <token_jwt_aqui>" \
  -d '{
    "userName": "studentuser",
    "password": "Studendt123!",
    "confirmPassword": "Studendt123!",
    "fullName": "Student User",
    "cui": "1234567890",
    "email": "student@example.com",
    "courseIds": [
      "string",
      "string2"
    ]
    }'


### Register User without Role
{
    "Name": "Student 1",
    "Email": "student1@example.com",
    "Password": "Student@123",
    "ConfirmPassword": "Student@123",
    "Role": ""
}

### Register User with Role
{
    "Name": "Student 2",
    "Email": "student2@example.com",
    "Password": "Student@123",
    "ConfirmPassword": "Student@123",
    "Role": "Student"
}

### Login as Admin
POST http://localhost:8001/api/auth/login
{
  "email": "admin@example.com",
  "password": "Admin@123"
}


### Login as Student
POST http://localhost:8001/api/auth/login
{
  "email": "student1@example.com",
  "password": "User@123"
}



### Create Admin
POST http://localhost:8001/api/admin/create
Content-Type: application/json

{
    "UserName": "adminuser",
    "Password": "securepassword123",
    "FullName": "John Admin",
    "Role": 1
}

### Create Student DONT WORKS
POST http://localhost:8001/api/user/create
Content-Type: application/json

{
    "UserName": "studentuser",
    "Password": "securepassword123",
    "FullName": "Jane Student",
    "Role": 0,
    "CUI": "CUI123456",
    "Email": "jane.student@example.com",
    "Courses": []
}



### Get Users Admins
GET  http://localhost:8001/api/admin/all

### Login and get Token
POST http://localhost:8001/api/authentication/login
Content-Type: application/json

{
    "userId": 1,
    "username": "adminuser"
}

# dotnet add package coverlet.msbuild

# dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
# test/test.csproj
# dotnet test test/test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura


## usario de prueba creacion
id = 0,
id = 2
creditos estudiante: 1
{
  "fullName": "Aldo Benito Martinez",
  "userData": {
    "userName": "bananon",
    "password": "Aldechi@123",
    "confirmPassword": "Aldechi@123",
    "role": "ADMIN"
  },
  "email": "aldechi001@example.com",
  "phoneNumber": "123456789"
}
